backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "people" # Used in routes, e.g., /admin/collections/blog
    label: "People" # Used in the UI
    folder: "src/data/people" # The path to the folder where the documents are stored
    extension: "json"
    create: true # Allow users to create new documents in this collection
    slug: "{{uid}}" # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: "uid"
    fields: # The fields for each document, usually in front matter
      - {label: "ID", name: "uid", widget: "string"}
      - {label: "Display Name", name: "displayName", widget: "string"}
  - name: "media" # Used in routes, e.g., /admin/collections/blog
    label: "Media" # Used in the UI
    folder: "src/data/media" # The path to the folder where the documents are stored
    extension: "json"
    create: true # Allow users to create new documents in this collection
    slug: "{{fields.slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: "slug"
    fields: # The fields for each document, usually in front matter
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}